let a=prompt('totalCash')
let b=prompt('watchesCount')
let c=prompt('earringsCount')
let bPrice=prompt('watch')
let cPrice=prompt('earring')
parseFloat(a)
parseInt(b)
parseInt(c)
parseFloat(bPrice)
parseFloat(cPrice)
let v=parseInt(b)*parseFloat(bPrice)
let w=parseInt(c)*parseFloat(cPrice)
let z=v+w
if (a>z) document.write('true')
else document.write('false')